// <auto-generated />
namespace TodayIHad.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class floattodouble : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(floattodouble));
        
        string IMigrationMetadata.Id
        {
            get { return "201609132156509_float to double"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
